#!/bin/bash -e
cd /tmp
curl -O http://www.lcdf.org/gifsicle/gifsicle-$GIFSICLE_VERSION.tar.gz
tar zxf gifsicle-$GIFSICLE_VERSION.tar.gz
cd gifsicle-$GIFSICLE_VERSION
./configure
make install
cd /
rm -fr /tmp/gifsicle*
